package tribixbite.cleverkeys.swipe

import ai.onnxruntime.OrtEnvironment
import android.content.Context
import android.net.Uri
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONObject
import org.junit.AfterClass
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith
import tribixbite.cleverkeys.langpack.ImportResult
import tribixbite.cleverkeys.langpack.LanguagePackManager
import tribixbite.cleverkeys.onnx.ModelLoader
import tribixbite.cleverkeys.swipe.ctc.CtcBeamDecoder
import tribixbite.cleverkeys.swipe.ctc.CtcFeaturizer
import tribixbite.cleverkeys.swipe.ctc.CtcLayout
import tribixbite.cleverkeys.swipe.ctc.CtcLexiconTrie
import tribixbite.cleverkeys.swipe.ctc.CtcPackModel
import tribixbite.cleverkeys.swipe.ctc.CtcScoringParams
import tribixbite.cleverkeys.swipe.ctc.CtcScriptSupport
import java.io.File
import java.io.FileOutputStream
import java.security.MessageDigest
import kotlin.math.abs

/**
 * G3 model-backed parity: every ONNX encoder in the APK, run through
 * [OnnxCtcEmissionModel], must reproduce the frozen features→emissions→top-k chain in its own
 * golden fixture (generated by CleverKeys-ML `ctc/make_golden.py` from the SAME artifact — each
 * fixture records its `source_onnx_sha256`).
 *
 * **This is the gate a model swap has to pass.** The pure `CtcParityTest` checks that the repo's
 * bytes hash to what the fixture claims; only this class actually RUNS the graph, so a swap that
 * updated a fixture's header but left its emission matrices stale is caught here and nowhere
 * else. It is in `.github/scripts/emulator-ci.sh`'s `CLASSES` for that reason.
 *
 * Since the multi-script wiring there is more than one encoder: the Latin
 * `models/ctc_swipe_encoder.onnx` plus one per wired script. A script is a ROW built from
 * [CtcScriptSupport], never a new mechanism — every fixture has the same shape and the beam
 * cases carry their own alphabet, lexicon and preset. All six script graphs are 589,406 B and
 * byte-size-identical to each other, so nothing but the sha can tell them apart, which is what
 * `shippedModelIsTheArtifactEachFixtureWasGeneratedFrom` asserts.
 *
 * ## Where each row's bytes come from (changed 2026-09-10)
 *
 * The Latin encoder is still an APK asset. The six script encoders left the APK and travel in
 * their language packs, so their rows stage the REAL shipped pack out of the test APK
 * (`copyScriptLatencyPacks`, byte-identical to `scripts/dictionaries/langpack-<code>.zip`), run
 * the SHIPPING importer over it, and then take the bytes back through
 * [CtcPackModel.verifiedPackModel] — the same call the adapter makes. That makes this gate
 * strictly stronger than reading an asset was: it now exercises the importer, the manifest hash
 * check and the app's pinned-sha gate on the way to running the graph, so a pack rebuilt without
 * its model, or with the wrong one, fails here as well as in `runPureTests`.
 *
 * Sessions are loaded with hardware acceleration DISABLED (plain ORT CPU EP) so
 * numerics are comparable to the desktop CPUExecutionProvider the fixtures were
 * generated with; export-time parity bounded |onnx−torch| at 3.8e-5 on the sliced
 * head (7.63e-05 for the ru generation-4 fp32 export, argmax 100/100), so EMISSION_TOL leaves
 * ample headroom for cross-platform libm drift while still catching any real wiring bug (wrong
 * tensor order, missing mask, bad slice, wrong graph for the language).
 */
@RunWith(AndroidJUnit4::class)
class CtcEmissionModelParityTest {

    /**
     * One (fixture, encoder) pair — a wired script is a ROW, never a new mechanism.
     *
     * @property modelAsset the encoder's LOGICAL name (`CtcEngineAdapter.modelAssetFor`), which
     *   is an APK asset path only when [packDelivered] is false.
     * @property packDelivered true when the bytes come from this language's imported pack.
     */
    private class Row(
        val language: String,
        val fixtureAsset: String,
        val modelAsset: String,
        val packDelivered: Boolean,
    ) {
        override fun toString(): String = language
    }

    companion object {
        private const val EMISSION_TOL = 2e-3
        private const val SCORE_TOL = 1e-3

        /**
         * The Latin encoder's row plus one per wired script, built from the SAME tables the
         * adapter dispatches through. A ROUTED script with no fixture cannot appear here and
         * fails `CtcScriptSupportTest` in `runPureTests` first.
         */
        private val ROWS: List<Row> = buildList {
            add(Row("en", "ctc/ctc_golden.json", CtcEngineAdapter.MODEL_ASSET, false))
            for ((language, wiring) in CtcScriptSupport.SCRIPTS) {
                val fixture = wiring.goldenFixture ?: continue
                add(
                    Row(
                        language, "ctc/$fixture", CtcEngineAdapter.modelAssetFor(language),
                        // A row with a pinned sha is pack-delivered by definition: the pin
                        // exists precisely because the bytes arrive from a user-supplied file.
                        packDelivered = wiring.modelSha256 != null,
                    )
                )
            }
        }

        private val models = HashMap<String, OnnxCtcEmissionModel>()
        private val goldens = HashMap<String, JSONObject>()

        @JvmStatic
        @BeforeClass
        fun setUp() {
            val target = InstrumentationRegistry.getInstrumentation().targetContext
            val testCtx = InstrumentationRegistry.getInstrumentation().context
            val env = OrtEnvironment.getEnvironment()
            for (row in ROWS) {
                goldens[row.language] = JSONObject(
                    testCtx.assets.open(row.fixtureAsset).readBytes().decodeToString()
                )
                if (row.packDelivered) importRealPack(target, row.language)
                // Hardware acceleration DISABLED (plain ORT CPU EP) so numerics are comparable
                // to the desktop CPUExecutionProvider the fixtures were generated with.
                val loader = ModelLoader(target, env)
                val loaded = if (row.packDelivered) {
                    loader.loadModel(
                        shippedModelBytes(target, row), "CtcEncoderParity-${row.language}",
                        enableHardwareAcceleration = false, xnnpackThreads = 1
                    )
                } else {
                    loader.loadModel(
                        row.modelAsset, "CtcEncoderParity-${row.language}",
                        enableHardwareAcceleration = false, xnnpackThreads = 1
                    )
                }
                models[row.language] = OnnxCtcEmissionModel(env, loaded.session)
            }
        }

        @JvmStatic
        @AfterClass
        fun tearDown() {
            for (model in models.values) model.close()
            models.clear()
            goldens.clear()
            // Leave the device as found: these packs are test fixtures here, not user installs.
            val target = InstrumentationRegistry.getInstrumentation().targetContext
            val manager = LanguagePackManager.getInstance(target)
            for (row in ROWS) {
                if (!row.packDelivered) continue
                manager.deletePack(row.language)
                CtcInstalledPacks.invalidate(target, row.language)
                File(target.cacheDir, "langpack-${row.language}.zip").delete()
            }
        }

        /** Stage the real pack out of the TEST APK's assets and run the shipping importer. */
        private fun importRealPack(target: Context, language: String) {
            val testAssets = InstrumentationRegistry.getInstrumentation().context.assets
            val zip = File(target.cacheDir, "langpack-$language.zip")
            testAssets.open("langpacks/langpack-$language.zip").use { input ->
                FileOutputStream(zip).use { input.copyTo(it) }
            }
            val result = LanguagePackManager.getInstance(target).importLanguagePack(Uri.fromFile(zip))
            assertTrue(
                "$language: importing the real langpack must succeed, got $result",
                result is ImportResult.Success
            )
            CtcInstalledPacks.invalidate(target, language)
        }

        /**
         * The bytes this row's encoder actually ships as, through the SAME resolution the
         * adapter uses. For a pack row that is [CtcPackModel.verifiedPackModel], so a pack whose
         * model fails the app's pinned-sha gate surfaces here as a missing model rather than as
         * a mysterious numeric mismatch further down.
         */
        private fun shippedModelBytes(target: Context, row: Row): ByteArray =
            if (row.packDelivered) {
                requireNotNull(CtcPackModel.verifiedPackModel(target.filesDir, row.language)) {
                    "${row.language}: the imported pack supplied no model that matches this " +
                        "app's pinned sha256 — rebuild langpack-${row.language}.zip with " +
                        "build_langpack.py --model"
                }
            } else {
                target.assets.open(row.modelAsset).use { it.readBytes() }
            }

        private fun fixtureLayout(language: String): CtcLayout {
            val lay = goldens.getValue(language).getJSONObject("layout")
            val letters = lay.getString("letters").toList()
            val cx = lay.getJSONArray("cx")
            val cy = lay.getJSONArray("cy")
            return CtcLayout.of(
                letters,
                List(cx.length()) { cx.getDouble(it).toFloat() },
                List(cy.length()) { cy.getDouble(it).toFloat() },
            )
        }
    }

    @Test
    fun emissions_matchGoldenWithinTolerance() {
        for (row in ROWS) emissionsRow(row)
    }

    private fun emissionsRow(row: Row) {
        val language = row.language
        val model = models.getValue(language)
        val golden = goldens.getValue(language)
        val padded = CtcFeaturizer.buildPaddedLayout(fixtureLayout(language))
        val cases = golden.getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = "$language/" + c.getString("name")
            val featJson = c.getJSONArray("features")
            val features = FloatArray(featJson.length()) { featJson.getDouble(it).toFloat() }

            val emissions = model.emit(features, padded)
            assertEquals("$name: frames", c.getInt("frames"), emissions.frames)
            assertEquals("$name: numClasses", c.getInt("numClasses"), emissions.numClasses)
            val rows = c.getJSONArray("emissions")
            var worst = 0.0
            for (t in 0 until emissions.frames) {
                val row = rows.getJSONArray(t)
                for (k in 0 until emissions.numClasses) {
                    val d = abs(emissions.at(t, k) - row.getDouble(k))
                    if (d > worst) worst = d
                }
            }
            assertTrue("$name: max |emissions - golden| = $worst", worst < EMISSION_TOL)
            checked++
        }
        assertTrue("$language: must exercise model-backed cases", checked > 0)
    }

    @Test
    fun endToEnd_featurizeEmitDecode_matchesGoldenTopK() {
        for (row in ROWS) endToEndRow(row)
    }

    private fun endToEndRow(row: Row) {
        val language = row.language
        val model = models.getValue(language)
        val golden = goldens.getValue(language)
        val layout = fixtureLayout(language)
        val padded = CtcFeaturizer.buildPaddedLayout(layout)
        val cases = golden.getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = "$language/" + c.getString("name")
            val pts = c.getJSONObject("points")
            val px = pts.getJSONArray("x"); val py = pts.getJSONArray("y")
            val pt = pts.getJSONArray("t")
            val features = CtcFeaturizer.featurize(
                DoubleArray(px.length()) { px.getDouble(it) },
                DoubleArray(py.length()) { py.getDouble(it) },
                DoubleArray(pt.length()) { pt.getDouble(it) },
            )
            // Featurizer must be bit-identical on-device too.
            val featJson = c.getJSONArray("features")
            for (k in features.indices) {
                assertEquals("$name: feature[$k]", featJson.getDouble(k).toFloat(), features[k], 0f)
            }

            val trie = CtcLexiconTrie(layout.alphabet.copyOf())
            val lex = c.getJSONArray("lexicon")
            for (j in 0 until lex.length()) {
                val e = lex.getJSONArray(j)
                trie.insert(e.getString(0), e.getDouble(1))
            }
            val p = c.getJSONObject("params")
            val params = CtcScoringParams(
                gamma = p.getDouble("gamma"), lambda = p.getDouble("lambda"),
                beta = p.getDouble("beta"), alpha = p.getDouble("alpha"),
                gammaPrune = p.getDouble("gammaPrune"), betaPrune = p.getDouble("betaPrune"),
                beamWidth = p.getInt("beamWidth"), topK = p.getInt("topK"),
            )
            val emissions = model.emit(features, padded)
            assertEquals("$name: greedy", c.getString("greedy"),
                CtcBeamDecoder.greedy(emissions, layout.alphabet))
            val result = CtcBeamDecoder.decode(emissions, trie, params)
            val expected = c.getJSONArray("topk")
            val expectedWords = (0 until expected.length())
                .map { expected.getJSONArray(it).getString(0) }
            assertEquals("$name: top-k words", expectedWords, result.map { it.word })
            for (k in result.indices) {
                assertEquals("$name: score[$k]",
                    expected.getJSONArray(k).getDouble(1), result[k].finalScore, SCORE_TOL)
            }
            checked++
        }
        assertTrue("$language: must exercise model-backed cases", checked > 0)
    }

    /**
     * Rule 4's first leg, checked against the artifact that actually ships: the bytes the device
     * ends up with must be the ones the fixture was generated from.
     *
     * All six script graphs are 589,406 B and byte-size-identical to each other, so size can
     * never discriminate them — only the sha256 can, and the pure `CtcParityTest` checks the
     * REPO copy while this checks what the device actually got: the packaged asset for en, and
     * for a script the bytes that survived the importer AND the app's pinned-sha gate.
     */
    @Test
    fun shippedModelIsTheArtifactEachFixtureWasGeneratedFrom() {
        val target = InstrumentationRegistry.getInstrumentation().targetContext
        val shaByLanguage = LinkedHashMap<String, String>()
        for (row in ROWS) {
            val bytes = shippedModelBytes(target, row)
            assertTrue("${row.language}: ${row.modelAsset} shipped empty", bytes.isNotEmpty())
            val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
            val sha = digest.joinToString("") { "%02x".format(it) }
            val expected = goldens.getValue(row.language)
                .getJSONArray("source_onnx_sha256").getString(0).lowercase()
            assertEquals(
                "${row.language}: sha256 of the SHIPPED ${row.modelAsset} must equal its " +
                    "fixture's source_onnx_sha256",
                expected, sha
            )
            shaByLanguage[row.language] = sha
        }
        // Every language must have its OWN graph. The script encoders are byte-size
        // identical, so a `modelAssetFor` that fell back to the Latin encoder — or two
        // fixtures regenerated from one artifact — would satisfy every per-row assertion
        // above and still route a script's swipes to the wrong graph.
        assertEquals(
            "two languages resolved to the same shipped encoder: $shaByLanguage",
            shaByLanguage.size, shaByLanguage.values.toSet().size
        )
    }

    /**
     * The parity gate must not be able to go vacuous. [ROWS] is derived from
     * [CtcScriptSupport.SCRIPTS], so a table edit that dropped a fixture reference would
     * silently shrink the set this class runs over — and every loop above would still pass.
     */
    @Test
    fun everyRoutedScriptIsParityChecked() {
        assertTrue("ROWS must never be empty — en is unconditional", ROWS.isNotEmpty())
        val checked = ROWS.map { it.language }.toSet()
        assertTrue("en must always be a parity row", "en" in checked)
        val routed = CtcScriptSupport.SCRIPTS
            .filterValues { it.status == CtcScriptSupport.Status.ROUTED }
            .keys
        assertTrue(
            "every ROUTED script must be model-parity checked here — rule 4 guarantees it " +
                "has a fixture, so a missing row means ROWS stopped picking them up. " +
                "ROUTED=$routed checked=$checked",
            checked.containsAll(routed)
        )
    }
}
