package tribixbite.cleverkeys.swipe

import ai.onnxruntime.OrtEnvironment
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONObject
import org.junit.AfterClass
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith
import tribixbite.cleverkeys.onnx.ModelLoader
import tribixbite.cleverkeys.swipe.ctc.CtcBeamDecoder
import tribixbite.cleverkeys.swipe.ctc.CtcFeaturizer
import tribixbite.cleverkeys.swipe.ctc.CtcLayout
import tribixbite.cleverkeys.swipe.ctc.CtcLexiconTrie
import tribixbite.cleverkeys.swipe.ctc.CtcScoringParams
import kotlin.math.abs

/**
 * G3 model-backed parity: the bundled `models/ctc_swipe_encoder.onnx`, run through
 * [OnnxCtcEmissionModel], must reproduce the frozen features→emissions→top-k chain
 * in `ctc/ctc_golden.json` (generated by CleverKeys-ML `ctc/make_golden.py` from
 * the SAME artifact — the fixture records its `source_onnx_sha256`).
 *
 * The session is loaded with hardware acceleration DISABLED (plain ORT CPU EP) so
 * numerics are comparable to the desktop CPUExecutionProvider the fixture was
 * generated with; export-time parity bounded |onnx−torch| at 3.8e-5 on the sliced
 * head, so EMISSION_TOL leaves ~50× headroom for cross-platform libm drift while
 * still catching any real wiring bug (wrong tensor order, missing mask, bad slice).
 */
@RunWith(AndroidJUnit4::class)
class CtcEmissionModelParityTest {

    companion object {
        private const val FIXTURE = "ctc/ctc_golden.json"
        private const val EMISSION_TOL = 2e-3
        private const val SCORE_TOL = 1e-3

        private lateinit var model: OnnxCtcEmissionModel
        private lateinit var golden: JSONObject

        @JvmStatic
        @BeforeClass
        fun setUp() {
            val target = InstrumentationRegistry.getInstrumentation().targetContext
            val testCtx = InstrumentationRegistry.getInstrumentation().context
            golden = JSONObject(
                testCtx.assets.open(FIXTURE).readBytes().decodeToString()
            )
            val env = OrtEnvironment.getEnvironment()
            val loaded = ModelLoader(target, env).loadModel(
                CtcEngineAdapter.MODEL_ASSET, "CtcEncoderParity",
                enableHardwareAcceleration = false, xnnpackThreads = 1
            )
            model = OnnxCtcEmissionModel(env, loaded.session)
        }

        @JvmStatic
        @AfterClass
        fun tearDown() {
            if (::model.isInitialized) model.close()
        }

        private fun fixtureLayout(): CtcLayout {
            val lay = golden.getJSONObject("layout")
            val letters = lay.getString("letters").toList()
            val cx = lay.getJSONArray("cx")
            val cy = lay.getJSONArray("cy")
            return CtcLayout.of(
                letters,
                List(cx.length()) { cx.getDouble(it).toFloat() },
                List(cy.length()) { cy.getDouble(it).toFloat() },
            )
        }
    }

    @Test
    fun emissions_matchGoldenWithinTolerance() {
        val padded = CtcFeaturizer.buildPaddedLayout(fixtureLayout())
        val cases = golden.getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = c.getString("name")
            val featJson = c.getJSONArray("features")
            val features = FloatArray(featJson.length()) { featJson.getDouble(it).toFloat() }

            val emissions = model.emit(features, padded)
            assertEquals("$name: frames", c.getInt("frames"), emissions.frames)
            assertEquals("$name: numClasses", c.getInt("numClasses"), emissions.numClasses)
            val rows = c.getJSONArray("emissions")
            var worst = 0.0
            for (t in 0 until emissions.frames) {
                val row = rows.getJSONArray(t)
                for (k in 0 until emissions.numClasses) {
                    val d = abs(emissions.at(t, k) - row.getDouble(k))
                    if (d > worst) worst = d
                }
            }
            assertTrue("$name: max |emissions - golden| = $worst", worst < EMISSION_TOL)
            checked++
        }
        assertTrue("must exercise model-backed cases", checked > 0)
    }

    @Test
    fun endToEnd_featurizeEmitDecode_matchesGoldenTopK() {
        val layout = fixtureLayout()
        val padded = CtcFeaturizer.buildPaddedLayout(layout)
        val cases = golden.getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = c.getString("name")
            val pts = c.getJSONObject("points")
            val px = pts.getJSONArray("x"); val py = pts.getJSONArray("y")
            val pt = pts.getJSONArray("t")
            val features = CtcFeaturizer.featurize(
                DoubleArray(px.length()) { px.getDouble(it) },
                DoubleArray(py.length()) { py.getDouble(it) },
                DoubleArray(pt.length()) { pt.getDouble(it) },
            )
            // Featurizer must be bit-identical on-device too.
            val featJson = c.getJSONArray("features")
            for (k in features.indices) {
                assertEquals("$name: feature[$k]", featJson.getDouble(k).toFloat(), features[k], 0f)
            }

            val trie = CtcLexiconTrie(layout.alphabet.copyOf())
            val lex = c.getJSONArray("lexicon")
            for (j in 0 until lex.length()) {
                val e = lex.getJSONArray(j)
                trie.insert(e.getString(0), e.getDouble(1))
            }
            val p = c.getJSONObject("params")
            val params = CtcScoringParams(
                gamma = p.getDouble("gamma"), lambda = p.getDouble("lambda"),
                beta = p.getDouble("beta"), alpha = p.getDouble("alpha"),
                gammaPrune = p.getDouble("gammaPrune"), betaPrune = p.getDouble("betaPrune"),
                beamWidth = p.getInt("beamWidth"), topK = p.getInt("topK"),
            )
            val emissions = model.emit(features, padded)
            assertEquals("$name: greedy", c.getString("greedy"),
                CtcBeamDecoder.greedy(emissions, layout.alphabet))
            val result = CtcBeamDecoder.decode(emissions, trie, params)
            val expected = c.getJSONArray("topk")
            val expectedWords = (0 until expected.length())
                .map { expected.getJSONArray(it).getString(0) }
            assertEquals("$name: top-k words", expectedWords, result.map { it.word })
            for (k in result.indices) {
                assertEquals("$name: score[$k]",
                    expected.getJSONArray(k).getDouble(1), result[k].finalScore, SCORE_TOL)
            }
            checked++
        }
        assertTrue("must exercise model-backed cases", checked > 0)
    }
}
