package tribixbite.cleverkeys.swipe

import ai.onnxruntime.OrtEnvironment
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONObject
import org.junit.AfterClass
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith
import tribixbite.cleverkeys.onnx.ModelLoader
import tribixbite.cleverkeys.swipe.ctc.CtcBeamDecoder
import tribixbite.cleverkeys.swipe.ctc.CtcFeaturizer
import tribixbite.cleverkeys.swipe.ctc.CtcLayout
import tribixbite.cleverkeys.swipe.ctc.CtcLexiconTrie
import tribixbite.cleverkeys.swipe.ctc.CtcScoringParams
import tribixbite.cleverkeys.swipe.ctc.CtcScriptSupport
import java.security.MessageDigest
import kotlin.math.abs

/**
 * G3 model-backed parity: every ONNX encoder in the APK, run through
 * [OnnxCtcEmissionModel], must reproduce the frozen features→emissions→top-k chain in its own
 * golden fixture (generated by CleverKeys-ML `ctc/make_golden.py` from the SAME artifact — each
 * fixture records its `source_onnx_sha256`).
 *
 * **This is the gate a model swap has to pass.** The pure `CtcParityTest` checks that the repo's
 * bytes hash to what the fixture claims; only this class actually RUNS the graph, so a swap that
 * updated a fixture's header but left its emission matrices stale is caught here and nowhere
 * else. It is in `.github/scripts/emulator-ci.sh`'s `CLASSES` for that reason.
 *
 * Since the multi-script wiring there is more than one encoder: the Latin
 * `models/ctc_swipe_encoder.onnx` plus one per wired script. A script is a ROW built from
 * [CtcScriptSupport], never a new mechanism — every fixture has the same shape and the beam
 * cases carry their own alphabet, lexicon and preset. All six script graphs are 589,406 B and
 * byte-size-identical to each other, so nothing but the sha can tell them apart, which is what
 * `packagedModelIsTheArtifactEachFixtureWasGeneratedFrom` asserts against the PACKAGED asset.
 *
 * Sessions are loaded with hardware acceleration DISABLED (plain ORT CPU EP) so
 * numerics are comparable to the desktop CPUExecutionProvider the fixtures were
 * generated with; export-time parity bounded |onnx−torch| at 3.8e-5 on the sliced
 * head (7.63e-05 for the ru generation-4 fp32 export, argmax 100/100), so EMISSION_TOL leaves
 * ample headroom for cross-platform libm drift while still catching any real wiring bug (wrong
 * tensor order, missing mask, bad slice, wrong graph for the language).
 */
@RunWith(AndroidJUnit4::class)
class CtcEmissionModelParityTest {

    /** One (fixture, model asset) pair — a wired script is a ROW, never a new mechanism. */
    private class Row(
        val language: String,
        val fixtureAsset: String,
        val modelAsset: String,
    ) {
        override fun toString(): String = language
    }

    companion object {
        private const val EMISSION_TOL = 2e-3
        private const val SCORE_TOL = 1e-3

        /**
         * The Latin encoder's row plus one per wired script, built from the SAME tables the
         * adapter dispatches through. A ROUTED script with no fixture cannot appear here and
         * fails `CtcScriptSupportTest` in `runPureTests` first.
         */
        private val ROWS: List<Row> = buildList {
            add(Row("en", "ctc/ctc_golden.json", CtcEngineAdapter.MODEL_ASSET))
            for ((language, wiring) in CtcScriptSupport.SCRIPTS) {
                val fixture = wiring.goldenFixture ?: continue
                add(Row(language, "ctc/$fixture", CtcEngineAdapter.modelAssetFor(language)))
            }
        }

        private val models = HashMap<String, OnnxCtcEmissionModel>()
        private val goldens = HashMap<String, JSONObject>()

        @JvmStatic
        @BeforeClass
        fun setUp() {
            val target = InstrumentationRegistry.getInstrumentation().targetContext
            val testCtx = InstrumentationRegistry.getInstrumentation().context
            val env = OrtEnvironment.getEnvironment()
            for (row in ROWS) {
                goldens[row.language] = JSONObject(
                    testCtx.assets.open(row.fixtureAsset).readBytes().decodeToString()
                )
                // Hardware acceleration DISABLED (plain ORT CPU EP) so numerics are comparable
                // to the desktop CPUExecutionProvider the fixtures were generated with.
                val loaded = ModelLoader(target, env).loadModel(
                    row.modelAsset, "CtcEncoderParity-${row.language}",
                    enableHardwareAcceleration = false, xnnpackThreads = 1
                )
                models[row.language] = OnnxCtcEmissionModel(env, loaded.session)
            }
        }

        @JvmStatic
        @AfterClass
        fun tearDown() {
            for (model in models.values) model.close()
            models.clear()
            goldens.clear()
        }

        private fun fixtureLayout(language: String): CtcLayout {
            val lay = goldens.getValue(language).getJSONObject("layout")
            val letters = lay.getString("letters").toList()
            val cx = lay.getJSONArray("cx")
            val cy = lay.getJSONArray("cy")
            return CtcLayout.of(
                letters,
                List(cx.length()) { cx.getDouble(it).toFloat() },
                List(cy.length()) { cy.getDouble(it).toFloat() },
            )
        }
    }

    @Test
    fun emissions_matchGoldenWithinTolerance() {
        for (row in ROWS) emissionsRow(row)
    }

    private fun emissionsRow(row: Row) {
        val language = row.language
        val model = models.getValue(language)
        val golden = goldens.getValue(language)
        val padded = CtcFeaturizer.buildPaddedLayout(fixtureLayout(language))
        val cases = golden.getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = "$language/" + c.getString("name")
            val featJson = c.getJSONArray("features")
            val features = FloatArray(featJson.length()) { featJson.getDouble(it).toFloat() }

            val emissions = model.emit(features, padded)
            assertEquals("$name: frames", c.getInt("frames"), emissions.frames)
            assertEquals("$name: numClasses", c.getInt("numClasses"), emissions.numClasses)
            val rows = c.getJSONArray("emissions")
            var worst = 0.0
            for (t in 0 until emissions.frames) {
                val row = rows.getJSONArray(t)
                for (k in 0 until emissions.numClasses) {
                    val d = abs(emissions.at(t, k) - row.getDouble(k))
                    if (d > worst) worst = d
                }
            }
            assertTrue("$name: max |emissions - golden| = $worst", worst < EMISSION_TOL)
            checked++
        }
        assertTrue("$language: must exercise model-backed cases", checked > 0)
    }

    @Test
    fun endToEnd_featurizeEmitDecode_matchesGoldenTopK() {
        for (row in ROWS) endToEndRow(row)
    }

    private fun endToEndRow(row: Row) {
        val language = row.language
        val model = models.getValue(language)
        val golden = goldens.getValue(language)
        val layout = fixtureLayout(language)
        val padded = CtcFeaturizer.buildPaddedLayout(layout)
        val cases = golden.getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = "$language/" + c.getString("name")
            val pts = c.getJSONObject("points")
            val px = pts.getJSONArray("x"); val py = pts.getJSONArray("y")
            val pt = pts.getJSONArray("t")
            val features = CtcFeaturizer.featurize(
                DoubleArray(px.length()) { px.getDouble(it) },
                DoubleArray(py.length()) { py.getDouble(it) },
                DoubleArray(pt.length()) { pt.getDouble(it) },
            )
            // Featurizer must be bit-identical on-device too.
            val featJson = c.getJSONArray("features")
            for (k in features.indices) {
                assertEquals("$name: feature[$k]", featJson.getDouble(k).toFloat(), features[k], 0f)
            }

            val trie = CtcLexiconTrie(layout.alphabet.copyOf())
            val lex = c.getJSONArray("lexicon")
            for (j in 0 until lex.length()) {
                val e = lex.getJSONArray(j)
                trie.insert(e.getString(0), e.getDouble(1))
            }
            val p = c.getJSONObject("params")
            val params = CtcScoringParams(
                gamma = p.getDouble("gamma"), lambda = p.getDouble("lambda"),
                beta = p.getDouble("beta"), alpha = p.getDouble("alpha"),
                gammaPrune = p.getDouble("gammaPrune"), betaPrune = p.getDouble("betaPrune"),
                beamWidth = p.getInt("beamWidth"), topK = p.getInt("topK"),
            )
            val emissions = model.emit(features, padded)
            assertEquals("$name: greedy", c.getString("greedy"),
                CtcBeamDecoder.greedy(emissions, layout.alphabet))
            val result = CtcBeamDecoder.decode(emissions, trie, params)
            val expected = c.getJSONArray("topk")
            val expectedWords = (0 until expected.length())
                .map { expected.getJSONArray(it).getString(0) }
            assertEquals("$name: top-k words", expectedWords, result.map { it.word })
            for (k in result.indices) {
                assertEquals("$name: score[$k]",
                    expected.getJSONArray(k).getDouble(1), result[k].finalScore, SCORE_TOL)
            }
            checked++
        }
        assertTrue("$language: must exercise model-backed cases", checked > 0)
    }

    /**
     * Rule 4's first leg, checked against the artifact that actually ships: the packaged ONNX
     * must be the same bytes the fixture was generated from.
     *
     * All six script graphs are 589,406 B and byte-size-identical to each other, so size can
     * never discriminate them — only the sha256 can, and the pure `CtcParityTest` checks the
     * REPO copy while this checks what aapt actually packaged.
     */
    @Test
    fun packagedModelIsTheArtifactEachFixtureWasGeneratedFrom() {
        val target = InstrumentationRegistry.getInstrumentation().targetContext
        for (row in ROWS) {
            val bytes = target.assets.open(row.modelAsset).use { it.readBytes() }
            val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
            val sha = digest.joinToString("") { "%02x".format(it) }
            val expected = goldens.getValue(row.language)
                .getJSONArray("source_onnx_sha256").getString(0).lowercase()
            assertEquals(
                "${row.language}: sha256 of the PACKAGED ${row.modelAsset} must equal its " +
                    "fixture's source_onnx_sha256",
                expected, sha
            )
        }
    }
}
