#!/usr/bin/env python3
"""
hprof_analyzer.py - Standalone Android HPROF Dump Analyzer

Parses Android 1.0.3 format HPROF dumps generated by Debug.dumpHprofData()
or am dumpheap without requiring third-party libraries (pure Python 3).

Supports:
- Instance census & shallow memory aggregation by class
- Object array and primitive array memory profiling
- Class name filtering
- Reverse reference tracing to identify retaining paths / roots
"""

import argparse
import os
import struct
import sys
from collections import defaultdict, deque

TYPE_NAMES = {
    2: "object",
    4: "boolean",
    5: "char",
    6: "float",
    7: "double",
    8: "byte",
    9: "short",
    10: "int",
    11: "long",
}

def type_size(t, id_size):
    if t == 2: return id_size  # OBJECT
    if t == 4: return 1        # BOOLEAN
    if t == 5: return 2        # CHAR
    if t == 6: return 4        # FLOAT
    if t == 7: return 8        # DOUBLE
    if t == 8: return 1        # BYTE
    if t == 9: return 2        # SHORT
    if t == 10: return 4       # INT
    if t == 11: return 8       # LONG
    raise ValueError(f"Unknown HPROF basic type: {t}")

class HprofParser:
    def __init__(self, path):
        self.path = path
        self.strings = {}
        self.classes = {}  # serial -> (class_obj_id, class_name_str_id)
        self.class_obj_to_name = {}
        self.class_fields = {}  # class_obj_id -> (super_id, [(name_id, type)])
        self.class_dump_body_sizes = {}
        self.heap_segments = []  # [(pos, data_pos, length)]
        self.id_size = 4
        self.id_fmt = ">I"

    def read_header_and_index(self, f):
        header = b""
        while True:
            c = f.read(1)
            if c == b"\x00" or not c:
                break
            header += c
        version_str = header.decode("latin1", errors="replace")
        self.id_size = struct.unpack(">I", f.read(4))[0]
        timestamp = struct.unpack(">Q", f.read(8))[0]
        self.id_fmt = ">I" if self.id_size == 4 else ">Q"

        print(f"HPROF Format: {version_str}, ID size: {self.id_size} bytes")

        while True:
            pos = f.tell()
            tag_b = f.read(1)
            if not tag_b:
                break
            tag = tag_b[0]
            _time = struct.unpack(">I", f.read(4))[0]
            length = struct.unpack(">I", f.read(4))[0]

            if tag == 0x01:  # STRING
                str_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                str_bytes = f.read(length - self.id_size)
                self.strings[str_id] = str_bytes.decode("latin1", errors="replace")
            elif tag == 0x02:  # LOAD CLASS
                serial = struct.unpack(">I", f.read(4))[0]
                class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                _stack_serial = struct.unpack(">I", f.read(4))[0]
                class_name_str_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                self.classes[serial] = (class_obj_id, class_name_str_id)
            elif tag in (0x0C, 0x1C):  # HEAP DUMP / HEAP DUMP SEGMENT
                self.heap_segments.append((pos, f.tell(), length))
                f.seek(length, 1)
            else:
                f.seek(length, 1)

        for serial, (class_obj_id, class_name_str_id) in self.classes.items():
            name = self.strings.get(class_name_str_id, f"unknown_str_{class_name_str_id}")
            self.class_obj_to_name[class_obj_id] = name.replace("/", ".")

    def run_census(self, filter_str=None, top_n=30):
        with open(self.path, "rb") as f:
            self.read_header_and_index(f)

            class_instances = defaultdict(int)
            class_instance_bytes = defaultdict(int)
            object_arrays = defaultdict(int)
            object_array_bytes = defaultdict(int)
            prim_arrays = defaultdict(int)
            prim_array_bytes = defaultdict(int)

            for seg_pos, data_pos, length in self.heap_segments:
                f.seek(data_pos)
                seg_end = data_pos + length
                while f.tell() < seg_end:
                    subtag = f.read(1)[0]
                    if subtag in (0xFF, 0x05, 0x07, 0x89, 0x8A, 0x8B, 0x8C, 0x8D):
                        f.seek(self.id_size, 1)
                    elif subtag in (0x01, 0x8E):
                        f.seek(self.id_size * 2, 1)
                    elif subtag in (0x02, 0x03, 0x08):
                        f.seek(self.id_size + 8, 1)
                    elif subtag in (0x04, 0x06):
                        f.seek(self.id_size + 4, 1)
                    elif subtag in (0xC8, 0x8F, 0xFE):
                        f.seek(4 + self.id_size, 1)
                    elif subtag == 0x20:  # CLASS DUMP
                        class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        _super_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        f.seek(self.id_size * 5 + 4, 1)  # class_loader, signers, prot_domain, 2*reserved, inst_size
                        cp_count = struct.unpack(">H", f.read(2))[0]
                        for _ in range(cp_count):
                            f.seek(2, 1)
                            cp_type = f.read(1)[0]
                            f.seek(type_size(cp_type, self.id_size), 1)
                        sf_count = struct.unpack(">H", f.read(2))[0]
                        for _ in range(sf_count):
                            f.seek(self.id_size, 1)
                            sf_type = f.read(1)[0]
                            f.seek(type_size(sf_type, self.id_size), 1)
                        if_count = struct.unpack(">H", f.read(2))[0]
                        f.seek(if_count * (self.id_size + 1), 1)
                    elif subtag == 0x21:  # INSTANCE DUMP
                        _obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        data_len = struct.unpack(">I", f.read(4))[0]
                        f.seek(data_len, 1)
                        class_instances[class_obj_id] += 1
                        class_instance_bytes[class_obj_id] += data_len
                    elif subtag == 0x22:  # OBJECT ARRAY DUMP
                        _obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        count = struct.unpack(">I", f.read(4))[0]
                        elem_class_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        f.seek(count * self.id_size, 1)
                        object_arrays[elem_class_id] += 1
                        object_array_bytes[elem_class_id] += count * self.id_size
                    elif subtag == 0x23:  # PRIMITIVE ARRAY DUMP
                        _obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        count = struct.unpack(">I", f.read(4))[0]
                        elem_type = f.read(1)[0]
                        sz = count * type_size(elem_type, self.id_size)
                        f.seek(sz, 1)
                        prim_arrays[elem_type] += 1
                        prim_array_bytes[elem_type] += sz
                    else:
                        print(f"Unknown subtag: 0x{subtag:02x} at {f.tell()-1}")
                        break

            print(f"\n================================================================================")
            print(f"TOP {top_n} CLASSES BY SHALLOW INSTANCE BYTES")
            print(f"================================================================================")
            sorted_classes = sorted(class_instance_bytes.items(), key=lambda x: x[1], reverse=True)
            shown = 0
            for class_id, total_bytes in sorted_classes:
                cname = self.class_obj_to_name.get(class_id, f"class_{hex(class_id)}")
                if filter_str and filter_str.lower() not in cname.lower():
                    continue
                cnt = class_instances[class_id]
                print(f"{cname:65s} | {cnt:8d} inst | {total_bytes / (1024 * 1024):7.2f} MB")
                shown += 1
                if shown >= top_n:
                    break

            print(f"\n================================================================================")
            print(f"PRIMITIVE ARRAYS")
            print(f"================================================================================")
            for elem_type, total_bytes in sorted(prim_array_bytes.items(), key=lambda x: x[1], reverse=True):
                tname = TYPE_NAMES.get(elem_type, f"type_{elem_type}")
                cnt = prim_arrays[elem_type]
                print(f"{tname:15s} | {cnt:8d} arrays | {total_bytes / (1024 * 1024):7.2f} MB")

            print(f"\n================================================================================")
            print(f"TOP OBJECT ARRAYS BY BYTES")
            print(f"================================================================================")
            sorted_obj_arr = sorted(object_array_bytes.items(), key=lambda x: x[1], reverse=True)
            for class_id, total_bytes in sorted_obj_arr[:15]:
                cname = self.class_obj_to_name.get(class_id, f"class_{hex(class_id)}")
                cnt = object_arrays[class_id]
                print(f"{cname:65s}[] | {cnt:8d} arrays | {total_bytes / (1024 * 1024):7.2f} MB")

    def trace_roots(self, target_class_name):
        with open(self.path, "rb") as f:
            self.read_header_and_index(f)

            target_class_ids = {cid for cid, name in self.class_obj_to_name.items() if target_class_name in name}
            print(f"Matching class IDs for '{target_class_name}': {[hex(c) for c in target_class_ids]}")
            if not target_class_ids:
                print("No matching classes found.")
                return

            # Pass 2: read class definitions and find target instance IDs
            target_instance_ids = set()
            for seg_pos, data_pos, length in self.heap_segments:
                f.seek(data_pos)
                seg_end = data_pos + length
                while f.tell() < seg_end:
                    subtag = f.read(1)[0]
                    if subtag in (0xFF, 0x05, 0x07, 0x89, 0x8A, 0x8B, 0x8C, 0x8D):
                        f.seek(self.id_size, 1)
                    elif subtag in (0x01, 0x8E):
                        f.seek(self.id_size * 2, 1)
                    elif subtag in (0x02, 0x03, 0x08):
                        f.seek(self.id_size + 8, 1)
                    elif subtag in (0x04, 0x06):
                        f.seek(self.id_size + 4, 1)
                    elif subtag in (0xC8, 0x8F, 0xFE):
                        f.seek(4 + self.id_size, 1)
                    elif subtag == 0x20:  # CLASS DUMP
                        class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        body_start = f.tell()
                        _stack = struct.unpack(">I", f.read(4))[0]
                        super_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        f.seek(self.id_size * 5 + 4, 1)
                        cp_count = struct.unpack(">H", f.read(2))[0]
                        for _ in range(cp_count):
                            f.seek(2, 1)
                            cp_type = f.read(1)[0]
                            f.seek(type_size(cp_type, self.id_size), 1)
                        sf_count = struct.unpack(">H", f.read(2))[0]
                        for _ in range(sf_count):
                            f.seek(self.id_size, 1)
                            sf_type = f.read(1)[0]
                            f.seek(type_size(sf_type, self.id_size), 1)
                        if_count = struct.unpack(">H", f.read(2))[0]
                        fields = []
                        for _ in range(if_count):
                            name_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                            f_type = f.read(1)[0]
                            fields.append((name_id, f_type))
                        self.class_fields[class_obj_id] = (super_id, fields)
                        self.class_dump_body_sizes[class_obj_id] = f.tell() - body_start
                    elif subtag == 0x21:  # INSTANCE DUMP
                        obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        data_len = struct.unpack(">I", f.read(4))[0]
                        if class_obj_id in target_class_ids:
                            target_instance_ids.add(obj_id)
                        f.seek(data_len, 1)
                    elif subtag == 0x22:  # OBJECT ARRAY DUMP
                        _obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        count = struct.unpack(">I", f.read(4))[0]
                        _elem_class_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        f.seek(count * self.id_size, 1)
                    elif subtag == 0x23:  # PRIMITIVE ARRAY DUMP
                        f.seek(self.id_size + 4, 1)
                        count = struct.unpack(">I", f.read(4))[0]
                        elem_type = f.read(1)[0]
                        f.seek(count * type_size(elem_type, self.id_size), 1)

            print(f"Found {len(target_instance_ids)} target instances: {[hex(i) for i in target_instance_ids]}")
            if not target_instance_ids:
                return

            # Pass 3: find incoming references
            direct_refs = defaultdict(list)
            for seg_pos, data_pos, length in self.heap_segments:
                f.seek(data_pos)
                seg_end = data_pos + length
                while f.tell() < seg_end:
                    subtag = f.read(1)[0]
                    if subtag in (0xFF, 0x05, 0x07, 0x89, 0x8A, 0x8B, 0x8C, 0x8D):
                        f.seek(self.id_size, 1)
                    elif subtag in (0x01, 0x8E):
                        f.seek(self.id_size * 2, 1)
                    elif subtag in (0x02, 0x03, 0x08):
                        f.seek(self.id_size + 8, 1)
                    elif subtag in (0x04, 0x06):
                        f.seek(self.id_size + 4, 1)
                    elif subtag in (0xC8, 0x8F, 0xFE):
                        f.seek(4 + self.id_size, 1)
                    elif subtag == 0x20:
                        class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        f.seek(self.class_dump_body_sizes[class_obj_id], 1)
                    elif subtag == 0x21:
                        obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        class_obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        data_len = struct.unpack(">I", f.read(4))[0]
                        data_end = f.tell() + data_len

                        curr_cls = class_obj_id
                        while curr_cls in self.class_fields:
                            sup_id, fields = self.class_fields[curr_cls]
                            for name_id, f_type in fields:
                                if f_type == 2:  # OBJECT
                                    val_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                                    if val_id in target_instance_ids:
                                        cname = self.class_obj_to_name.get(class_obj_id, f"class_{hex(class_obj_id)}")
                                        fname = self.strings.get(name_id, f"field_{name_id}")
                                        direct_refs[val_id].append((obj_id, f"{cname}#{fname}"))
                                else:
                                    f.seek(type_size(f_type, self.id_size), 1)
                            curr_cls = sup_id
                        f.seek(data_end)
                    elif subtag == 0x22:
                        obj_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        _stack = struct.unpack(">I", f.read(4))[0]
                        count = struct.unpack(">I", f.read(4))[0]
                        elem_class_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                        for idx in range(count):
                            elem_id = struct.unpack(self.id_fmt, f.read(self.id_size))[0]
                            if elem_id in target_instance_ids:
                                cname = self.class_obj_to_name.get(elem_class_id, "Object")
                                direct_refs[elem_id].append((obj_id, f"{cname}[{idx}]"))
                    elif subtag == 0x23:
                        f.seek(self.id_size + 4, 1)
                        count = struct.unpack(">I", f.read(4))[0]
                        elem_type = f.read(1)[0]
                        f.seek(count * type_size(elem_type, self.id_size), 1)

            print(f"\n================================================================================")
            print(f"INCOMING REFERENCES TO INSTANCES OF {target_class_name}")
            print(f"================================================================================")
            for t_id in target_instance_ids:
                refs = direct_refs[t_id]
                print(f"\nInstance {hex(t_id)} (Total incoming refs: {len(refs)}):")
                for src_id, label in refs:
                    src_type = self.class_obj_to_name.get(src_id, f"obj_{hex(src_id)}")
                    print(f"  <- from {hex(src_id)} ({label})")

def main():
    parser = argparse.ArgumentParser(description="Standalone Android HPROF Dump Analyzer")
    parser.add_argument("hprof_path", help="Path to .hprof file")
    parser.add_argument("--filter", "-f", help="Filter class names in census", default=None)
    parser.add_argument("--top", "-n", type=int, default=30, help="Number of top classes to display")
    parser.add_argument("--trace", "-t", help="Trace incoming references to class name", default=None)

    args = parser.parse_args()
    if not os.path.isfile(args.hprof_path):
        print(f"Error: File not found: {args.hprof_path}", file=sys.stderr)
        sys.exit(1)

    analyzer = HprofParser(args.hprof_path)
    if args.trace:
        analyzer.trace_roots(args.trace)
    else:
        analyzer.run_census(filter_str=args.filter, top_n=args.top)

if __name__ == "__main__":
    main()
