package tribixbite.cleverkeys.swipe.ctc

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import java.io.File
import java.security.MessageDigest
import org.json.JSONObject
import org.junit.Test
import tribixbite.cleverkeys.Defaults
import tribixbite.cleverkeys.swipe.CtcEngineAdapter

/**
 * Golden-trace parity tests for the pure-JVM FUTO-style CTC swipe module.
 *
 * The authoritative expectations live in `src/test/resources/ctc/ctc_golden.json`, frozen
 * from the SAME Python port this module is a Kotlin port of
 * (`scripts/futo_decoder_eval.py` featurizer + greedy CTC, `futo_decoder_ceiling.py`'s
 * `futo_viterbi_beam`). Each fixture case feeds a hand-crafted input through both ports and
 * this test asserts the Kotlin decode matches:
 *  - **featurize** cases: the exact `[2,64]` path tensor (bit-identical float32).
 *  - **beam** cases: identical greedy-CTC string, identical top-k WORDS (the core ranking
 *    parity), and top-k final SCORES within a tight float tolerance (`Math.pow`/`ln` differ
 *    from the C-libm the port uses by at most ~1 ULP, so exact score equality is not
 *    asserted — word order is).
 *
 * The fixture is regenerated by `scratchpad/gen_ctc_golden.py`; the input matrices are
 * committed so this half of the gate is self-contained and runs with no model and no
 * device. The other half — that the SHIPPED encoder actually produces those emissions
 * through ORT — is the instrumented `swipe/CtcEmissionModelParityTest`.
 */
class CtcParityTest {

    private companion object {
        /** Project-root-relative (runPureTests runs with cwd = project root, per GeoLayoutFixtures). */
        const val GOLDEN_PATH = "src/test/resources/ctc/ctc_golden.json"

        /** The instrumented copy the on-device parity gate reads from test assets. */
        const val GOLDEN_ASSET_PATH = "src/androidTest/assets/ctc/ctc_golden.json"

        /**
         * The shipped emission encoder the fixture was generated from.
         *
         * DERIVED from `CtcEngineAdapter.MODEL_ASSET` rather than hardcoded: the whole point of
         * this test is that the fixture, the model and the preset move together, so a fixture
         * check that reads a DIFFERENT path than the app loads can pass while the app ships a
         * different model. Renaming the asset must break this test, not slip past it.
         */
        val MODEL_ASSET_PATH = "src/main/assets/" + CtcEngineAdapter.MODEL_ASSET

        /** Score parity: word order is exact; scores tolerate libm pow/log drift. */
        const val SCORE_TOL = 1e-4
    }

    private fun loadGolden(): JSONObject {
        val f = File(GOLDEN_PATH)
        assertWithMessage("golden fixture must exist at $GOLDEN_PATH (regenerate via " +
            "scratchpad/gen_ctc_golden.py)").that(f.exists()).isTrue()
        return JSONObject(f.readText())
    }

    // ── Featurizer parity ─────────────────────────────────────────────────────────

    @Test
    fun featurizer_matchesPythonPort_bitIdentical() {
        val cases = loadGolden().getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "featurize") continue
            val name = c.getString("name")
            val pts = c.getJSONObject("points")
            val px = pts.getJSONArray("x").toDoubleArray()
            val py = pts.getJSONArray("y").toDoubleArray()
            val pt = pts.getJSONArray("t").toDoubleArray()

            val out = CtcFeaturizer.featurize(px, py, pt)
            val expected = c.getJSONArray("features")
            assertWithMessage("$name: feature length").that(out.size).isEqualTo(expected.length())
            for (k in out.indices) {
                // The stored JSON value is a float32 widened to double; .toFloat() recovers
                // the exact float32, so an EXACT match proves bit-identical featurization.
                assertWithMessage("$name: feature[$k] (bit-identical to port)")
                    .that(out[k]).isEqualTo(expected.getDouble(k).toFloat())
            }
            checked++
        }
        assertWithMessage("must have exercised featurizer cases").that(checked).isGreaterThan(0)
    }

    // ── Beam + greedy parity ──────────────────────────────────────────────────────

    @Test
    fun beam_matchesPythonPort_greedyAndTopK() {
        val cases = loadGolden().getJSONArray("cases")
        var checked = 0
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val name = c.getString("name")

            val alphabet = c.getString("alphabet").toCharArray()
            val frames = c.getInt("frames")
            val numClasses = c.getInt("numClasses")
            val emissions = readEmissions(c.getJSONArray("emissions"), frames, numClasses)
            val trie = buildTrie(alphabet, c.getJSONArray("lexicon"))
            val params = readParams(c.getJSONObject("params"))

            // Greedy CTC parity.
            val greedy = CtcBeamDecoder.greedy(emissions, alphabet)
            assertWithMessage("$name: greedy").that(greedy).isEqualTo(c.getString("greedy"))

            // Beam top-k parity.
            val result = CtcBeamDecoder.decode(emissions, trie, params)
            val expected = c.getJSONArray("topk")
            val expectedWords = (0 until expected.length()).map { expected.getJSONArray(it).getString(0) }
            val gotWords = result.map { it.word }
            assertWithMessage("$name: top-k words (got $gotWords, want $expectedWords)")
                .that(gotWords).isEqualTo(expectedWords)
            for (k in result.indices) {
                assertWithMessage("$name: final score[$k] (${result[k].word})")
                    .that(result[k].finalScore).isWithin(SCORE_TOL)
                    .of(expected.getJSONArray(k).getDouble(1))
            }
            checked++
        }
        assertWithMessage("must have exercised beam cases").that(checked).isGreaterThan(0)
    }

    // ── The fixture-and-preset rule (CleverKeys-ML MODEL_COMPARISON.md §5.1) ──────

    /**
     * **Model, preset and fixture move together — always.**
     *
     * The fixture records the artifact it was generated from (`source_onnx_sha256`) and
     * the preset it was generated at (`preset`). Shipping the model at one preset and
     * the fixture at another means the parity gate asserts against a configuration
     * nothing runs — the exact failure mode `MODEL_COMPARISON.md` §5.1 exists to
     * prevent, and the one that put an E1-generated fixture next to an app-preset model
     * mid-campaign (`PHASE_M.md` §11.1, "Fixture correction").
     *
     * This is the pure-JVM half of the gate and it needs no device: it pins all three
     * corners of the triangle. The instrumented `CtcEmissionModelParityTest` covers the
     * fourth thing only a device can check — that the artifact actually *produces* the
     * fixture's emissions through ORT.
     *
     * Current ship state (CleverKeys-ML `ctc/UNSEALING_4.md`, `ctc/PHASE_M.md` §11.1):
     * `phaseM_kd_fresh_w1_s1234_fp16w.onnx` sha `84718e6e…`, fixture
     * `phaseM_kd_fresh_w1_fp16w_golden.json` sha `2a449c4f…`, preset
     * `0.9 / 4.0 / 0.25 / 0.25 / 0.9882` = [CtcScoringParams.tunedV2].
     */
    @Test
    fun fixture_model_and_shipPreset_travelTogether() {
        val golden = loadGolden()

        // 1. The fixture's preset IS the runtime ship preset (tunedV2), term by term.
        //    The fixture stores the five scoring terms alpha omits (it is unused by the
        //    CTC core): [gamma, lambda, beta, gammaPrune, betaPrune].
        val preset = golden.getJSONArray("preset")
        val ship = CtcScoringParams.tunedV2()
        assertWithMessage("fixture preset must have the 5 scoring terms").that(preset.length())
            .isEqualTo(5)
        assertWithMessage("fixture gamma vs tunedV2").that(preset.getDouble(0)).isEqualTo(ship.gamma)
        assertWithMessage("fixture lambda vs tunedV2").that(preset.getDouble(1)).isEqualTo(ship.lambda)
        assertWithMessage("fixture beta vs tunedV2").that(preset.getDouble(2)).isEqualTo(ship.beta)
        assertWithMessage("fixture gammaPrune vs tunedV2").that(preset.getDouble(3))
            .isEqualTo(ship.gammaPrune)
        assertWithMessage("fixture betaPrune vs tunedV2").that(preset.getDouble(4))
            .isEqualTo(ship.betaPrune)

        // 1b. beamWidth is NOT one of the five scoring terms, and until 2026-08-20 nothing
        //     pinned it — so the fixture could be generated at a different width from the one
        //     the app decodes at and this test would still pass. That gap matters because
        //     width changes which candidates survive pruning, i.e. exactly what parity is
        //     supposed to be checking. The fixture is deliberately narrow (cheap to generate
        //     over a 7-word lexicon); what must hold is that the SHIP width is the validated
        //     one, since every campaign accuracy number was decoded at it.
        assertWithMessage(
            "the ship preset's beamWidth must equal Defaults.CTC_BEAM_WIDTH — that is the " +
                "width every published accuracy number was decoded at, and the settings " +
                "default must not drift away from it"
        ).that(ship.beamWidth).isEqualTo(Defaults.CTC_BEAM_WIDTH)

        // 2. Every beam case decodes at that same preset (a case generated at another
        //    preset would silently weaken the parity assertion above it).
        val cases = golden.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            if (c.getString("kind") != "beam") continue
            val p = readParams(c.getJSONObject("params"))
            assertWithMessage("${c.getString("name")}: beam case must use the ship preset")
                .that(listOf(p.gamma, p.lambda, p.beta, p.gammaPrune, p.betaPrune))
                .isEqualTo(listOf(ship.gamma, ship.lambda, ship.beta, ship.gammaPrune, ship.betaPrune))
        }

        // 3. The bundled ONNX asset IS the artifact the fixture was generated from.
        val model = File(MODEL_ASSET_PATH)
        assertWithMessage("shipped encoder must exist at $MODEL_ASSET_PATH")
            .that(model.exists()).isTrue()
        val expectedSha = golden.getJSONArray("source_onnx_sha256").getString(0).lowercase()
        assertWithMessage(
            "sha256($MODEL_ASSET_PATH) must equal the fixture's source_onnx_sha256 — the " +
                "shipped model and the golden fixture must be the same artifact"
        ).that(sha256(model)).isEqualTo(expectedSha)

        // 4. The instrumented copy is byte-identical, so the device gate asserts the
        //    same contract this one does.
        val asset = File(GOLDEN_ASSET_PATH)
        assertWithMessage("instrumented fixture copy must exist at $GOLDEN_ASSET_PATH")
            .that(asset.exists()).isTrue()
        assertWithMessage(
            "$GOLDEN_ASSET_PATH must be byte-identical to $GOLDEN_PATH (one fixture, two " +
                "consumers: runPureTests reads resources, the device gate reads test assets)"
        ).that(sha256(asset)).isEqualTo(sha256(File(GOLDEN_PATH)))
    }

    // ── Helpers ───────────────────────────────────────────────────────────────────

    private fun sha256(f: File): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(f.readBytes())
        return digest.joinToString("") { "%02x".format(it) }
    }

    private fun org.json.JSONArray.toDoubleArray(): DoubleArray =
        DoubleArray(length()) { getDouble(it) }

    private fun readEmissions(rows: org.json.JSONArray, frames: Int, numClasses: Int): CtcEmissions {
        val values = FloatArray(frames * numClasses)
        for (t in 0 until frames) {
            val row = rows.getJSONArray(t)
            for (c in 0 until numClasses) {
                values[t * numClasses + c] = row.getDouble(c).toFloat()
            }
        }
        return CtcEmissions(values, frames, numClasses)
    }

    private fun buildTrie(alphabet: CharArray, lexicon: org.json.JSONArray): CtcLexiconTrie {
        val trie = CtcLexiconTrie(alphabet)
        // Insert in list order so child-edge ordering matches the port exactly.
        for (i in 0 until lexicon.length()) {
            val entry = lexicon.getJSONArray(i)
            trie.insert(entry.getString(0), entry.getDouble(1))
        }
        return trie
    }

    private fun readParams(p: JSONObject): CtcScoringParams =
        CtcScoringParams(
            gamma = p.getDouble("gamma"),
            lambda = p.getDouble("lambda"),
            beta = p.getDouble("beta"),
            alpha = p.getDouble("alpha"),
            gammaPrune = p.getDouble("gammaPrune"),
            betaPrune = p.getDouble("betaPrune"),
            beamWidth = p.getInt("beamWidth"),
            topK = p.getInt("topK"),
        )
}
